name: Validación de Inventario

on: [push]

jobs:
  check-inventario:
    runs-on: windows-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Manuel se está durmiendo
        run: sleep 4
        
      - name: Mostrar contenido del inventario
        run: cat inventario.csv

      - name: Para saber la hora
        run: date

      - name: quiero saber si después de la instalación funciona la página
        run: curl -k https://as.com